### ISSUE TITLE
No settings wrench on iphone 

### ISSUE THREAD

**Issue by simpat1zq** [LazeMSS/OctoPrint-UICustomizer#20]
[
 ENTER DESCRIPTION HERE- ALSO ADD SCREENSHOT IF POSSIBLE!
 Describe your problem?
 What is the problem?
 Can you recreate it?
 Did you try disabling plugins?
 Did you remeber to update the subject?
]

**Plugins installed:**
- DeleteAfterPrint
- PrintJobHistory
- PrintTimeGenius
- UltimakerFormatPackage
- action_command_notification
- action_command_prompt
- announcements
- astroprint
- backup
- bedlevelingwizard
- bedlevelvisualizer
- cancelobject
- errortracking
- gcodeviewer
- klipper
- mqtt
- navbartemp
- octopod
- pluginmanager
- preheat
- resource_monitor
- softwareupdate
- statefulsidebar
- tplinksmartplug
- uicustomizer
- virtual_printer

**Software versions:**
- OctoPrint 1.5.1
- Python 3.6.9

**Comment by LazeMSS** [comment]
Could you try and describe a bit more?
What happens if you swipe to the right - is the wrench icon anywhere to be seen?

**Comment by simpat1zq** [comment]
I’ve tried all sorts of tapping everywhere, swiping, and rotating the screen. I can’t get it to show.

**Comment by simpat1zq** [comment]
I updated to the latest version 0.1.1.1 and I still don't see the wrench. The top bar does look cleaner as there is nothing overflowing below it. It also doesn't show the temps when I have the phone in portrait mode, but the show up in landscape. The wrench just doesn't show up.

**Comment by LazeMSS** [comment]
> I updated to the latest version 0.1.1.1 and I still don't see the wrench. The top bar does look cleaner as there is nothing overflowing below it. It also doesn't show the temps when I have the phone in portrait mode, but the show up in landscape. The wrench just doesn't show up.
One or more of the plugins you have installed add a lot of stuff to the menu or topbar.

**Comment by LazeMSS** [comment]
@simpat1zq  please test with latest version (https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.1.2)

**Comment by simpat1zq** [comment]
Still doesn’t show up. And now if ‘compact navbar’ is enabled it doesn’t show the temperature number, only the icons. If I turn that off it shows the temperature. But still no settings wrench.

**Comment by LazeMSS** [comment]
Here is how it looks on my iphone - could you look into your plugins and try disabling them - as I wrote earlier:
"One or more of the plugins you have installed add a lot of stuff to the menu or topbar. I can try and install them all but if you have a guess which one it would be easier"

![131027047_745551106312741_1389973211324638514_n](https://user-images.githubusercontent.com/69049371/102022102-dac12300-3d84-11eb-89f1-24c54c58f775.jpg)

**Comment by LazeMSS** [comment]
@simpat1zq  What menu settings do you have enabled in UI Customizer... Im guessing you dont have enabled the responsive option?

**Comment by simpat1zq** [comment]
I havent had a chance to disable plugins yet. Im printing an order and its going to take another day. The only thing i have unchecked is fixed header and fixed footer.

**Comment by LazeMSS** [comment]
@simpat1zq  should be fixed in https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.1.5 - if not then reopen please 👍

**Comment by simpat1zq** [comment]
I updated. It didn't work until I disabled 'Center Topbar Icons' and 'Improve Mobile/Responsiveness'. And then I see the wrench. Enabling Compact Menu doesn't seem to do anything. It still shows the wrench/power/username icons separately. The compact menu doesn't seem to work on mobile or on desktop. Let me know if you want me to create a new issue for this or if you consider it the same issue.

**Comment by LazeMSS** [comment]
And you are running on the latest version? I would not recommend running without improve mobile if you use it from a mobile.

The wrench and other menu items are always on the right hand side. The compact menu only works when in mobile responsive mode.

Try pressing the report a bug in settings and I will get all the data and I can test but I think my plugin is working as I expect but not like you want it to 😄

Maybe drop a screenshot etc

**Comment by simpat1zq** [comment]
This is on the latest version of this plugin as of 10 minutes ago. I disabled most plugins. There are no icons now other than the octoprint logo on the top left. 
![93CAB1DF-7BDC-4BA6-A170-91E0A84A5134](https://user-images.githubusercontent.com/22940871/102349483-626b8500-3f71-11eb-94fb-fe7ada3f115b.png)

I had to pull the bug report from my PC. I get the same issue in safari iOS and the chrome app on iOS, which is probably expected. 

Please let me know if there is any other information you might need. 
[
 ENTER DESCRIPTION HERE- ALSO ADD SCREENSHOT IF POSSIBLE!
 Describe your problem?
 What is the problem?
 Can you recreate it?
 Did you try disabling plugins?
 Did you remeber to update the subject?
]

**Plugins installed:**
- action_command_notification
- action_command_prompt
- announcements
- backup
- gcodeviewer
- mqtt
- pluginmanager
- softwareupdate
- uicustomizer


**Plugin settings:**
- addWebCamZoom: true
- centerTopIcons: false
- compactMenu: true
- disableTermInactive: true
- fixedFooter: false
- fixedHeader: false
- fluidLayout: true
- hideGraphBackground: true
- hideMainCam: true
- mainTabsCustomize: true
- navbarplugintempfix: true
- responsiveMode: true


**Software versions:**
- OctoPrint 1.5.2
- Python 3.6.9

**Browser:**
-Mozilla/5.0 (Windows NT 10.0 Win64 x64 rv:83.0) Gecko/20100101 Firefox/83.0

**Comment by LazeMSS** [comment]
Please update to the latest version: 0.1.1.5 - please try and update.

Goto Settings -> Software update: Advanced options - and click the force check

**Comment by simpat1zq** [comment]
I’m already on that version

**Comment by LazeMSS** [comment]
I have the identical settings on my iPhone and I cant recreate that no matter how hard I try :(

**Comment by simpat1zq** [comment]
There might be something strange going on with my OP install then. It must have started recently too. The files take like 20 seconds to load. I disabled your plugin and it is still the same way.

**Comment by LazeMSS** [comment]
Take a look in the developer console with your pc or the logs in the settings

**Comment by simpat1zq** [comment]
So I figured out that there was a plugin from a while ago that added something in the announcements section. And the place they were pulling from is down so it didn’t load some stuff until that time out. 

After disabling the announcement, octoprint is back to normal, but I still don’t see any icons at the top with this plugin. I even removed the plugin with a clean uninstall and reinstalled it and the same thing happens.

**Comment by LazeMSS** [comment]
> So I figured out that there was a plugin from a while ago that added something in the announcements section. And the place they were pulling from is down so it didn’t load some stuff until that time out.
> 
> After disabling the announcement, octoprint is back to normal, but I still don’t see any icons at the top with this plugin. I even removed the plugin with a clean uninstall and reinstalled it and the same thing happens.

And nothing in the developer console or anything else - does it look okay if you resize your browser size on a computer?

**Comment by simpat1zq** [comment]
Here’s some output from the dev console. If I make my desktop browser smaller, the icons for octoprint disappear. And the dev console doesn’t say anything new when I resize. 

Firefox can’t establish a connection to the server at ws://192.168.45.104:5000/sockjs/451/5eig4l2r/websocket. packed_libs.js:1232:25077
Some cookies are misusing the recommended “SameSite“ attribute 59
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.
3 192.168.45.104:5000
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.
192.168.45.104:5000
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. 192.168.45.104:5000
Less has finished and no sheets were loaded. packed_libs.js:1249:143043
HTTP “Content-Type” of “text/html” is not supported. Load of media resource http://192.168.45.104:5000/ failed.

**Comment by LazeMSS** [comment]
Do you have an external octoprint I can try on?

**Comment by simpat1zq** [comment]
No not external. Did you want to do a screen share?

**Comment by LazeMSS** [comment]
> No not external. Did you want to do a screen share?

Yes if possible email me at:
uicust
at
jemi
.
dk

remove newlines and replace at with @ 👍

**Comment by LazeMSS** [comment]
Bug found - next release will fix this :)

**Comment by LazeMSS** [comment]
Should be fixed in https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.1.7
Please try and if not fixed then reopen this issue.
