### ISSUE TITLE
Maximized webcam stream doesn't care about browser height.

### ISSUE THREAD

**Issue by Akegata** [LazeMSS/OctoPrint-UICustomizer#26]
If I have my browser in a 1:1 aspect ratio or less (for example 1:2) the maximized webcam stream is fully visible, although not filling as much of the browser as possible.
When I change the browser size to something like 16:9, the stream gets to big vertically to see all of the picture, and also makes it impossible to minimize the stream since that icon dissapears.
It seems like it's set to always be a specific number of pixels from the left and right sides of the browser since that doesn't change when the browser size is changed, but not to the top and bottom sides.

**Comment by Akegata** [comment]
1:1(ish) aspect ratio:
![Capture](https://user-images.githubusercontent.com/4068947/101986192-ecbf9a80-3c8c-11eb-8f54-39e64b1d88e9.PNG)

2:1(ish) aspect ratio:
![Capture](https://user-images.githubusercontent.com/4068947/101986221-06f97880-3c8d-11eb-8d01-34ca6993918d.PNG)

**Comment by LazeMSS** [comment]
I can see you are using the "FullScreen webcam plugin" - that adds a lot of extra stuff to the bottom of the webcam - my plugin doesn't take that extra stuff into consideration - I will try and look if its possible

**Comment by LazeMSS** [comment]
I maybe I can fix - will try and include it in next release

**Comment by LazeMSS** [comment]
@Akegata 
Please confirm its fixed in the latest release:
https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.1.3
... if so then feel free to close this - thanks.

**Comment by Akegata** [comment]
I just updated to 0.1.1.3 and also removed the Fullscreen Webcam plugin to avoid issues.
It is better now, it works great on normal 16:9 screens, but on my ultrawide 21:9 screen, the issue is still there.

**Comment by LazeMSS** [comment]
The issue still being there is the problem with webcam being hiden behind the topbar?

**Comment by LazeMSS** [comment]
I have tried to fix it a bit better in the next release

**Comment by LazeMSS** [comment]
Please report browser size and webcam sizes

**Comment by holocronology** [comment]
Screen: 1920x1080
Browers size (?): full screen
Webcam: PiCam v2.1, I think, 16:9

Is this what you need?

**Comment by LazeMSS** [comment]
The output resoultion on that cam should be 1920x1080 i think - so similar to mine.
Can you post a screenshot of what looks wrong?

**Comment by holocronology** [comment]
@LazeMSS I did in the one you closed. Here it is again: https://user-images.githubusercontent.com/65265114/102084416-bdb73f00-3dda-11eb-856f-1e43400dc3c0.png

**Comment by LazeMSS** [comment]
I meant fullscreen - I cant figure out why the overlay window is higher than the screen - it should never happen - and you are running the latest 0.1.1.3?

**Comment by Akegata** [comment]
I don't know what the webcame video size is for me. I guess it's probably 1920x1080 for me a well, but not sure if that matters since it scales with the browser size anyway?
This is what it looks like for me when I have the browser in fullscreen on my monitor with 3440x1440 resolution.
![Capture](https://user-images.githubusercontent.com/4068947/102095062-5bcef780-3e23-11eb-85ce-052e54e53fd1.PNG)

**Comment by LazeMSS** [comment]
Firefox?

**Comment by Akegata** [comment]
It's a normal Logitech something webcam.

But you are onto something with the browser. I tested in both Chrome and Edge as well, there the webcam window doesn't extend behind the topbar.

**Comment by LazeMSS** [comment]
Firefox is broken with something with the normal webcam streams - I will try more :)

**Comment by muenznej** [comment]
just wanted to mention that i got the same problem with the fullscreen webstream not scaling properly.

**Comment by LazeMSS** [comment]
0.1.1.4 release out now - should hopefully fix these problems - please test :)

**Comment by Akegata** [comment]
Well, it's definitely better since it doesn't go underneath the topbar, which means the minimize button is accessible. However, the resize is still weird, it doesn't care about the lower part of the screen now.

The print bed should be visible, but the lower part of the image is cut.

![Capture](https://user-images.githubusercontent.com/4068947/102139567-4dea9800-3e5e-11eb-8cfd-243bcb9319f2.PNG)

**Comment by LazeMSS** [comment]
I cant figure out why - there shouldn't be any cache ie in the browser.
This is on my Firefox with a simulated screen similar to yours
![image](https://user-images.githubusercontent.com/69049371/102142105-27c6f700-3e62-11eb-9794-95ec1303bf2a.png)

**Comment by holocronology** [comment]
Looks like a lot of others have weighed in. Here's the full screen you asked for: 
![image](https://user-images.githubusercontent.com/65265114/102144166-a4d67a00-3e2a-11eb-9110-2da2acaebcea.png)

**Comment by LazeMSS** [comment]
To check for the latest update got into:
Settings -> Software update. At the bottom of the page press "Advanced options" and then " Force check for update (overrides cache used for update checks)"

@Akegata  can you try this aswell?

**Comment by Akegata** [comment]
@LazeMSS I'm not sure if I understand what you mean, it looks like your example is cropped in the same way as mine?
The latest picture I posted was with 0.1.1.4.

**Comment by LazeMSS** [comment]
yes you are right - I need to get some sleep - will look a bit more tomorrow

**Comment by LazeMSS** [comment]
@Akegata / @holocronology   should be fixed in https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.1.5 - if not then reopen please 👍

**Comment by Akegata** [comment]
Yup, works great now! Thanks!

**Comment by holocronology** [comment]
Also confirming fixed in FireFox.

**Comment by muenznej** [comment]
all fine. gj and thx
