### ISSUE TITLE
Drop-down menu hidden behind main tabs

### ISSUE THREAD

**Issue by Merhim** [LazeMSS/OctoPrint-UICustomizer#34]
Hi,
The central drop-down menu in the top-bar are hidden by the main tabs, so they are difficult to reach.
Thanks for your work
 
![Tab1](https://user-images.githubusercontent.com/76015321/102143081-b38d5300-3e63-11eb-82b6-bbc04f8f5b59.PNG)

**Comment by LazeMSS** [comment]
There seems to be a problem with something overlaying the mains tabs - maybe another plugin. 

But I need more information - what other plugins are you using?
What settings in my plugin?
And what version of my plugin are you using?

**Comment by LazeMSS** [comment]
From my installation: 
![image](https://user-images.githubusercontent.com/69049371/102144810-6c549180-3e66-11eb-9905-a1189e0ead14.png)

**Comment by Merhim** [comment]
Everything works when "Fixed header/topbar" is selected or "Center topbar icons" is not selected.
The problem remains in the configuration below

UI Customizer version: 0.1.1.4 

![Plugin](https://user-images.githubusercontent.com/76015321/102145617-d7529800-3e67-11eb-974f-8c84924767be.PNG)

**Comment by LazeMSS** [comment]
Found the bug - will fix it in the next release

**Comment by LazeMSS** [comment]
@Merhim should be fixed in https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.1.5 - if not then reopen please 👍

**Comment by Merhim** [comment]
Hi Laze,
I have just updated UICustomizer to the new v0.1.1.6, but i still have the same bug as before.

![Bug](https://user-images.githubusercontent.com/76015321/102719490-c635db00-42ee-11eb-838a-3fffae8715d5.PNG)
![Settings](https://user-images.githubusercontent.com/76015321/102719503-d8177e00-42ee-11eb-9108-3b3ee773c942.PNG)

**Comment by Merhim** [comment]
As before the problem only occurs when the header/topbar is not fixed.

Thank you so much for you effort  👍

**Comment by LazeMSS** [comment]
Should be fixed in https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.1.7
Please try and if not fixed then reopen this issue.
