### ISSUE TITLE
Gcode viewer doesn't fit the dedicated area

### ISSUE THREAD

**Issue by Lecl0ne** [LazeMSS/OctoPrint-UICustomizer#43]
In a column width of 5 (and maybe 4 too btw), the G-code viewer is not optimized and is smaller than it can be, see screenshot

![GcodeV](https://user-images.githubusercontent.com/42405376/103070294-84908300-45c1-11eb-82a5-9dfc0cce9b26.png)

Can you recreate it? It's column width dependant.

<hr>

**Plugins installed**
- ProgressBasedOntime Plugin[ProgressBasedOnTime] v0.1.6
- Friendly Neighborhood Beeper[FriendlyBeeper] v0.4.0
- Marlin GCode Documentation[marlingcodedocumentation] v0.11.0
- Fullscreen Plugin[fullscreen] v0.0.6
- Cancel Objects[cancelobject] v0.4.4
- Auto Terminal Input[AutoTerminalInput] v0.1.0
- Themeify[themeify] v1.2.2
- Autoscroll[autoscroll] v0.0.3
- Terminal Messaging[terminalmessaging] v0.1.0
- **UI Customizer[uicustomizer] v0.1.1.8**
- Autoselect Plugin[autoselect] v0.3.0
- Autologin Configuration[autologin_config] v0.2.0
- M117NavBar[M117NavBar] v0.1.1
- Printoid Plugin[printoid] v1.0.2
- Bed Visualizer[bedlevelvisualizer] v1.0.0
- SetAndWait[setandwait] v0.0.1
- Progress Title[progress_title] v0.1.1
- Detailed Progress[detailedprogress] v0.2.6
- GCODE System Commands[gcodesystemcommands] v1.0.1
- Cura Thumbnails[UltimakerFormatPackage] v0.2.1
- Preheat Button[preheat] v0.5.1
- Multi Line Terminal[multilineterminal] v0.1.5
- SpoolManager Plugin[SpoolManager] v1.2.0
- Cost Estimation[costestimation] v3.1.0
- Active Filters Extended[active_filters_extended] v0.1.0
- PrintTimeGenius Plugin[PrintTimeGenius] v2.2.7
- Arc-Welder[arc_welder] v1.0.0+u.bb71e8f
- Octolapse[octolapse] v0.4.1

**UI Customizer settings**
- addWebCamZoom: false
- centerTopIcons: true
- compactMenu: false
- disableTermInactive: true
- fixedFooter: false
- fixedHeader: true
- fluidLayout: true
- hideGraphBackground: true
- hideMainCam: false
- mainTabsCustomize: true
- navbarplugintempfix: true
- responsiveMode: false

**Software versions**
- OctoPrint 1.5.2
- Python 2.7.16
- OctoPi 0.17.0

**Browser**
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.66

**Comment by LazeMSS** [comment]
Yes I stepped back from using full width due to the aspect ratio of the gcode causing the controls to slip to the bottom. I might add it as a feature.

**Comment by Lecl0ne** [comment]
> causing the controls to slip to the bottom.

Can you show the problem in a screenshot ?

**Comment by LazeMSS** [comment]
Fixed in 0.1.1.9(https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.1.9)
- please check and reopen/comment if not working as expected.

**Comment by Lecl0ne** [comment]
Hey Laze,

Problem still here for me after enabling your new option:

![Gcode](https://user-images.githubusercontent.com/42405376/103537032-e8555e80-4e93-11eb-8dc6-5d926a7bf413.png)

**Comment by LazeMSS** [comment]
Tried refreshing? it works fine - I haven't tried your layout but you can check using the developer tools, inspector if you know how

**Comment by Lecl0ne** [comment]
I tried refreshing, wiping cache etc.. I dont know about inspector :(

**Comment by LazeMSS** [comment]
Right click on the gcode viewer and select inspect. It will show you a lot info take a screenshot of that

**Comment by LazeMSS** [comment]
I have tried on all my computers and devices. In the next version the preview will show when its applied. I noticed you are runinng 0.1.18 on the bug report and using the fullscreen plugin. There might be problems.

Anyway after next release please try again.

**Comment by Lecl0ne** [comment]
Still the same. You're right. It's about "Fluid/full width layout" option. When enabled, it's not ok...

**Comment by LazeMSS** [comment]
Can you take a screenshot view preview on and toggling it on/off - here how it looks on my pc:

Without:
![image](https://user-images.githubusercontent.com/69049371/103804830-fe5d4d80-5052-11eb-9205-910200d0f8e5.png)

With:
![image](https://user-images.githubusercontent.com/69049371/103804866-06b58880-5053-11eb-9e77-37f1f302df10.png)

**Comment by LazeMSS** [comment]
@Lecl0ne ?

**Comment by Lecl0ne** [comment]
Yep sorry I was busy. I'll do it.

**Comment by Lecl0ne** [comment]
Here it is:

Full width On / G-code fullsize On
![With](https://user-images.githubusercontent.com/42405376/104058921-c2fa8480-51f4-11eb-9a27-d1c99a38953d.png)

Full width On / G-code fullsize Off
![Without](https://user-images.githubusercontent.com/42405376/104058952-cb52bf80-51f4-11eb-9c78-06de331f6fea.png)

Full width Off / G-code fullsize On
![Full width off - With](https://user-images.githubusercontent.com/42405376/104058971-d3126400-51f4-11eb-9539-4df4d4443795.png)

Full width Off / G-code fullsize Off
![Full width off - Without](https://user-images.githubusercontent.com/42405376/104059002-df96bc80-51f4-11eb-9681-acbf8d80b00a.png)

**Comment by LazeMSS** [comment]
Have you tried different layouts ? Ie tried having the gcode in the center like mine - just to rule that out?

But my guess is that another plugin is installed that also changes in the way the gcode viewer is handled

**Comment by Lecl0ne** [comment]
I'll give it a try.. :/

**Comment by LazeMSS** [comment]
Thanks :)

**Comment by LazeMSS** [comment]
Ahh FOUND it - you have disabled responsive mode

**Comment by LazeMSS** [comment]
Waiting to close after release

**Comment by Lecl0ne** [comment]
Nope.
![Screenshot_20210109-045318](https://user-images.githubusercontent.com/42405376/104082452-abdc8680-5236-11eb-97b3-1e97b11b1a2f.png)

**Comment by LazeMSS** [comment]
So still not working when you have responsive mode on?
From your original post it looked like you didn't have that on - and I made an error on the full widt only work with this.

**Comment by Lecl0ne** [comment]
Screenshots are with responsive mode ON.

**Comment by LazeMSS** [comment]
Then I have no idea. Judging from your screenshots https://github.com/LazeMSS/OctoPrint-UICustomizer/issues/43#issuecomment-756966159

The difference in sizes show that symptoms based on improved mobile responsive disable

**Comment by LazeMSS** [comment]
Closing - should be fixed in https://github.com/LazeMSS/OctoPrint-UICustomizer/releases/tag/0.1.2.4

@Lecl0ne  if not fixed then please reopen this and post screenshots as before

**Comment by Lecl0ne** [comment]
Hey,

It's still exactly the same since the update.

**Comment by LazeMSS** [comment]
I have no idea why this is happening

**Comment by Lecl0ne** [comment]
Is there any plugin I should try to disable ?

**Comment by Lecl0ne** [comment]
Something interesting is that the size of the area changes with the Chrome explorer zoom:

100%
![100](https://user-images.githubusercontent.com/42405376/104313633-925a6980-54d8-11eb-882b-0fdd70c3dfdb.png)

50%
![50](https://user-images.githubusercontent.com/42405376/104313637-938b9680-54d8-11eb-8ff8-b33a9a6415c9.png)

125%
![125](https://user-images.githubusercontent.com/42405376/104313639-938b9680-54d8-11eb-899f-885c88b86b8b.png)

**Comment by Lecl0ne** [comment]
Found it !!!! Compatibility problem with Cancel Object Plugin !

**Comment by LazeMSS** [comment]
I was wondering if that plugin changes anything to the canvas

**Comment by Lecl0ne** [comment]
Bug still here with new update.

**Comment by LazeMSS** [comment]
I have not tried with the cancel object plugin

**Comment by LazeMSS** [comment]
Fixed in next version and supporting cancel object :)

**Comment by Lecl0ne** [comment]
Well done!!!

**Comment by codefaux** [comment]
Hey so I found this trying to find what was causing a similar issue with a -different- layout plugin. This plugin looks way better though lol -- is this fixed or nah?

**Comment by LazeMSS** [comment]
This should be fixed yes
